### ISSUE TITLE
[Feature request] Infer console_ui_loglevel from `--log <level>` command-line argument

### ISSUE THREAD

**Issue by user202729** [psethwick/plover_tui#12]
Is it possible? Or is it only parsed by Plover?

I only figure out the configuration option by reading the source code.

It's also kind of a bug too, since the flag is silently discarded.

**Comment by psethwick** [comment]
I was not actually aware of that option

I think it should be possible, probably sys.argv isn't cleared by plover

(Also I agree: bug)

**Comment by psethwick** [comment]
Having second thoughts on 'bug'

--log-level applies to the default logger (e.g. out to the log file). I think the argument is being honoured correctly.

Whereas the loglevel command (and related "console_ui_loglevel") setting applies to what gets printed in the console UI.

I definitely need to document the difference though
