### ISSUE TITLE
Wrong chained should not enter the submenu?

### ISSUE THREAD

**Issue by user202729** [psethwick/plover_tui#13]
I'm not entirely sure if this is a bug or a feature.

Example: If I type `col error`, "Unsupported command: error" is printed, but I'm moved to menu "colors".

While if I type a complete command `col for white`, I remains in the current (top) level.

**Comment by psethwick** [comment]
I think bug! It's probably time to get some automated tests on the commands bit

**Comment by psethwick** [comment]
Pushed a change for this. 

Let me know what you think, it feels a bit weird that 'Unsupported command' only shows the last part of it.

E.g. for your example `col error` it seems like it maybe should print "Unsupported command: col error"

**Comment by psethwick** [comment]
Should all be done now, I fixed that weirdness ^^
