### ISSUE TITLE
How to show error message traceback in the console?

### ISSUE THREAD

**Issue by user202729** [psethwick/plover_tui#19]
(currently, it can only be read from plover.log file.)

Reproduce: make some plugin that throws an error (?)

Perhaps adding an nonexistent dictionary (or delete an existing dictionary) is easier.

**Comment by psethwick** [comment]
Ah, turns out I'm using the NoExceptionTracebackFormatter from plover/log.py
Might just... not
Fix shortly!

**Comment by psethwick** [comment]
Released as 1.1.2
