### ISSUE TITLE
Console window scrolling is inconsistent when there's line wrap

### ISSUE THREAD

**Issue by user202729** [psethwick/plover_tui#20]
(title)

Sometimes it scroll more than one page, which makes it impossible to view some part of the content.

I only notice the bug because I have dictionaries with very long path and occasionally not-very-large console width.

Given that it use scroll_down() and scroll_up() of prompt_toolkit directly, it's more likely a prompt_toolkit bug.

**Comment by psethwick** [comment]
Actually pretty sure the bug is mine, I will have a dig on how scrolling is implemented upstream (but I'm not using it directly)

**Comment by psethwick** [comment]
there must be some way to detect wrapping and scroll accordingly
(have not found it, but now it only scrolls 2/3 of screen height, so it ought to be better)
Release 1.1.3
Let me know if this works better!

**Comment by psethwick** [comment]
Gonna close this, if it's still an issue please raise!
