### ISSUE TITLE
ADD TRANSLATION to specific dictionary 

### ISSUE THREAD

**Issue by robert-winkler** [psethwick/plover_tui#21]
Your plugin is exactly what I needed for my X-free steno machine!
But how can I add an entry to a specific dictionary?
Best, Robert

**Comment by psethwick** [comment]
Glad to hear it!

Currently the behaviour is: add to the top-priority dictionary

Would you want to configure it or choose it on the fly?

Both are possible, suspect choosing will be more flexible, but slightly trickier to implement

**Comment by robert-winkler** [comment]
Hi, the best would be to choose the dictionary case-by-case.

For example, a new translation could fit into the vim dictionary, the
personal English dictionary, ...

If this is difficult, I just would define a file for collecting new
translations, and sort them later.

Quoting Seth Rider (2021-05-05 07:41:19)

**Comment by psethwick** [comment]
Yeah, I think that would also be best, really!

Shouldn't be hard, I just have to be careful with focus :-) I'll have a go sometime this week.

**Comment by psethwick** [comment]
I've got something working here: https://github.com/psethwick/plover_console_ui/tree/choose-dict-addtranslation

Would you like to test it out @robert-winkler and see how it feels? 
(Assuming you're comfy enough with git/pip/plover to install from a random branch-- if not let me know!) 
(Hm, I might try and work out how to do `pre-release` builds on pypi for pull requests, might be fun)

I still need to document it, but roughly, for now:
  Tab, Shift-Tab still swaps between Strokes, Translation and the 'Add To' fields
  If you're in the 'Add To' field, left-arrow and right-arrow will cycle through (writable!) dictionaries

I'll find some time tomorrow for docs, tidy up, etc, but I don't _think_ there are any glaring issues.

I find it a little annoying that the cursor is at the beginning of the 'Add To' field, so I might fix that

**Comment by psethwick** [comment]
Released with 1.2.0!
