### ISSUE TITLE
doesn't work with plover master

### ISSUE THREAD

**Issue by dnaq** [psethwick/plover_tui#23]
The following commit from plover https://github.com/openstenoproject/plover/commit/f29fe041e45c05084b149e6a5aa60846866825ae changed how gui plugins are called. Now they take an extra controller object as a parameter. Since the plugin doesn't expect that parameter the call to `plugin.main()` fails.

**Comment by psethwick** [comment]
Oh cool breaking changes...

Shouldn't be too hard to sort out tho, I'll fix it up later!
