### ISSUE TITLE
How to send output to Bluetooth/USB

### ISSUE THREAD

**Issue by robert-winkler** [psethwick/plover_tui#27]
Hi, thanks for this great program!

I'm running the console UI on several PCs, including a Raspberry Pi 0 W with a 7-inch display
![PXL_20211003_143839948](https://user-images.githubusercontent.com/9994605/144331897-ac5866d3-2222-4e54-8097-3cf28c693461.jpg)
I published the 3D printing files at [Thingiverse](https://www.thingiverse.com/thing:4860013).

It would be great to send the output directly to another machine, for example using Bluetooth. The [Stenogotchi](https://github.com/Anodynous/stenogotchi) has this function but is not very flexible concerning hardware.

Would it be possible to add a Bluetooth or USB connection for external devices?

**Comment by user202729** [comment]
I don't think this is an issue with this plugin, although the pending Plover plugin https://github.com/openstenoproject/plover/pull/1276 can do it. For now there are options to monkey-patch Plover API to do what you want, see e.g. https://github.com/user202729/plover-uinput-output .

**Comment by psethwick** [comment]
sorry, I've been pretty busy!

Babies, am I right

**Comment by psethwick** [comment]
I would agree this is pretty out of scope for a UI in general (and this plugin in particular)

@user202729's suggestions seem reasonable to me

You could also install the bluetooth bits of Stenogotchi as a plugin directly and use this UI. It does _look_ like that part is possibly installable as a plugin already. If it's not, it's probably less work hacking that together than monkey patching plover
