### ISSUE TITLE
Add a fully headless mode

### ISSUE THREAD

**Issue by paulmw** [psethwick/plover_tui#30]
Please consider adding a fully headless mode. I was hoping to use this without in the Linux console, but it still requires a terminal window.

**Comment by psethwick** [comment]
Does --gui none do what you want?

Without a window into it I think this plugin doesn't really offer anything useful

**Comment by paulmw** [comment]
I have a Linux console open, but I’m not running X so there’s no terminal.
Full screen text mode applications such as vim and mc work as expected, but
this plugin fails since it can’t find the X display:

ERROR: error loading gui plugin: console (from plover_console_ui.plugin)
…
Xlib.error.DisplayNameError: Bad display name “”

From the trace back it looks like the console UI is calling commander, then
commands, then application, then layout. That then ends up calling wmctl,
xwmctl etc, which ends up depending on X.

**Comment by paulmw** [comment]
Interestingly, plover -g none has the same problem, though a different
traceback. In that case, main ends up calling xkeyboardcontrol.py, which
fails due to no display being available.

**Comment by psethwick** [comment]
Unfortunately the current implementation of plover has a hard dependency on X (XLib specifically)

You'd have to do some serious hacking on the plover source to fix that
