### ISSUE TITLE
Installation Instructions Update

### ISSUE THREAD

**Issue by alikhatibak** [psethwick/plover_tui#32]
### Issue Summary
README may benefit from additional information for new users regarding the `plover` command.

After installing the `plover_console_ui` plugin from the plugin manager, attempting to run the plugin using `plover --gui console` raised the error `command not found: plover`.

Additional info in docs may help users troubleshoot this error

### Expected Behavior
The plugin should run without any errors using the `plover -g console` command.

### Actual Behavior
Running the plugin raises a `command not found: plover` error.

### Additional Information
As per the [Plover Docs](https://plover.readthedocs.io/en/latest/cli_reference.html), the `plover` command is available under slightly different names on each platform, relative to your installation directory:

- **Windows**: `C:\Program Files (x86)\Open Steno Project\Plover 4.0.0\plover_console.exe`
- **macOS**: `/Applications/Plover.app/Contents/MacOS/Plover`
- **Linux**: `plover.AppImage`

The docs also use the `-g` flag instead of the `--gui` flag. Although quite minor, I included it as part of this issue.

It would also be nice for those not familiar with installing plugins through the command line to be able to copy the `plover -s plover_plugins install plover_console_ui` command from the docs, as well as a direct link to the Command Line Reference Docs linked above.

As a relatively new Plover user, I think this documentation update could help prevent the troubleshooting steps of finding this solution for other users interested in using this phenomenal plugin.

**Comment by alikhatibak** [comment]
Included a pull request to resolve this issue [here](https://github.com/psethwick/plover_console_ui/pull/33)!

**Comment by psethwick** [comment]
thank you! merged

**Comment by alikhatibak** [comment]
@psethwick Of course! Thank you for creating such a great plugin!
