### ISSUE TITLE
Plover printing info/error messages messes up the window layout

### ISSUE THREAD

**Issue by user202729** [psethwick/plover_tui#4]
It isn't very hard to make Plover print out an error message. Having a dictionary missing or a mapping (in keyboard configuration -- need the other gui to control the keyboard) undefined is sufficient.

(these issues only apply to the TUI version, which appears to not have much development -- I didn't figure out that there's a console branch.)

Special case: if a extension prints out something, it still mess up the window layout (although this is probably impossible to prevent)

**Comment by psethwick** [comment]
the TUI (asciimatics) version won't be supported in the future (so will close this and the other TUI-only issues)
hopefully extensions tend to post messages to the log instead of directly printing, but yeah, not a lot I can do I don't think

**Comment by user202729** [comment]
It's still possible to reassign the sys.stdout and sys.stderr objects and handle that, but that's not easy.
