### ISSUE TITLE
`remove` in subprompt `dictionaries > 1 >` should automatically move up a level (console version)

### ISSUE THREAD

**Issue by user202729** [psethwick/plover_tui#5]
I know that experienced users can simply do `1 remove` from the `dictionaries >` layer, but they have to learn that `remove` should be used in the first place.

Remark: unlike the qt version, this version still add the dictionary to the console if `dictionaries add` is used, despite the error. (which I assume is because it doesn't do the error checking that the qt file picker does, and let Plover handle it)

**Comment by psethwick** [comment]
I think this is a good call! I'll do something like this, or I may move `remove` up a level and have it take an argument
   (so it would be `dictionaries remove 1` instead)

I don't _quite_ follow your remark, I gather gui_qt does some error checking that I'm not, but not sure of scenario?

**Comment by user202729** [comment]
If I try to select something like `/tmp/` to add as a dictionary, the console will allow it (then Plover will print an error message), but the qt one won't (because the file picker only allow selecting existing files)

**Comment by psethwick** [comment]
ah ok, that should be pretty straightforward

eventually I will probably get some context-aware autocomplete in for paths/commands/etc
