### ISSUE TITLE
Confusing old output in `dictionaries` menu

### ISSUE THREAD

**Issue by user202729** [psethwick/plover_tui#9]
Not really an issue, but this is confusing.

Example:

* User type `dictionaries`. All dictionaries are printed.
* User type `priority 1 2` or `remove 1`. Nothing is printed.  The old list of dictionaries is still visible on the screen.

I see some options in this case.

1. Print the dictionaries on every change by the user. (perhaps preferred)
2. Print a status message ("Priority changed", etc.)
3. Make a separate window for the dictionaries list.

**Comment by psethwick** [comment]
I also think the behaviour is weird. 
I have tried out option 1 already (which I also prefer) but having some async/thread interaction problems

Have also considered having a dictionaries window, which would honestly solve the async problem, but not sure I really love it.

Will try for option 1 still I think, just need to solve my race conditions somehow. Maybe I'll hook/unhook dictionaries_changed

**Comment by psethwick** [comment]
Was tripped up before by the `dictionaries_loaded` hook only being called _once_

Should work now, they do show up in config_changed, so I'm using that

**Comment by psethwick** [comment]
Fun side effect (which I'm counting as a feature): 
- if anything alters the dictionaries (say with plover_dict_commands)
    - the new state gets printed to consoel
